import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useEffect, useState } from "react";
import io from "socket.io-client";

const socket = io();

const Home: NextPage = (): JSX.Element => {
  const [isConnected, setIsConnected] = useState(socket.connected);
  const [locations, setLocations] = useState<string[]>([]);

  useEffect(() => {
    socketInitializer();
  });

  const socketInitializer = async () => {
    await fetch("/api/hello"); // connect to API

    socket.on("connect", () => {
      setIsConnected(true);
    });

    socket.on("disconnect", () => {
      setIsConnected(false);
    });

    const success = (pos: {
      coords: { latitude: any; longitude: any };
    }): void => {
      var crd = pos.coords;

      const userLocation: string = `${crd.latitude}, ${crd.longitude}`;
      console.log(userLocation);  // debugging

      // Get other's geolocation
      socket.on("update-locations", (msg): void => {
        // Ensure that the response is not my location
        if (msg != userLocation) {
          setLocations([...locations, msg]);
        }
      });

      // Send user geolocation to socket
      socket.emit("other-locations", userLocation);
    };

    const error = (err: { code: any; message: any }): void => {
      console.warn(`ERROR(${err.code}): ${err.message}`);
      navigator.geolocation.clearWatch(id);
    };

    // Configure geolocation for high accuracy
    const options = {
      enableHighAccuracy: true,
      timeout: 5000,
      maximumAge: 0
    };

    // Start recording user geolocation
    let id = navigator.geolocation.watchPosition(success, error, options);
  };

  // Contain all the locations as HTML content
  const locationsInHtml = locations.map((value) => (
    <p key={value} className={styles.card}>
      {value}
    </p>
  ));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js!</h1>

        <div className={styles.grid}>{locationsInHtml}</div>
      </main>
    </div>
  );
};

export default Home;
