import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useEffect, useState } from "react";
import io from "socket.io-client";

const Home: NextPage = (): JSX.Element => {
  const [locations, setLocations] = useState("");

  useEffect(() => {
    socketInitializer();
  }, []);

  const socketInitializer = async () => {
    await fetch("/api/hello"); // connect to API
    let socket = io();

    // Get user geolocation
    navigator.geolocation.getCurrentPosition((position): void => {
      let location: string = `${position.coords.latitude}, ${position.coords.longitude}`;
      socket.emit("other-locations", location); // send geolocation to socket
    });

    // Get other's geolocation
    socket.on("update-locations", (msg): void => {
      setLocations(msg);
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js!</h1>

        <div className={styles.grid}>
          <p className={styles.card}>{locations}</p>

          <p className={styles.card}>
            Learn about Next.js in an interactive course with quizzes!
          </p>

          <p className={styles.card}>
            Discover and deploy boilerplate example Next.js projects.
          </p>

          <p className={styles.card}>
            Instantly deploy your Next.js site to a public URL with Vercel.
          </p>
        </div>
      </main>
    </div>
  );
};

export default Home;
